name: aoc21
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
- directory >= 1.3
- regex-tdfa >= 1.3
- containers >= 0.5
- split >= 0.2
- timeit >= 2.0
- psqueues == 0.2.7.3

executables:
  aoc21:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -O3
