name: aoc21
version: 0.1.0.0

dependencies:
- base >= 4.7 && < 5
- directory >= 1.3
- regex-tdfa >= 1.3
- containers >= 0.5

executables:
  aoc21:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -O3
